### ISSUE TITLE
IMG kit crashes 50% of the time when trying to generate image from highcharts 

### ISSUE THREAD

**Issue by Shopwiz** [csquared/IMGKit#76]
Hello, 

Here is the error I get when trying to generate a image (.png) from an highchart graph. I don't think it has something to do with highcharts since we sometimes (more rarely) have errors when generating PDF as well. 

Can you please fix or help us with this problem? 
Thanks, 
WizVille team. 

No live threads left. Deadlock?
/home/wizville/.rbenv/versions/2.1.5/lib/ruby/2.1.0/open3.rb:262:in `value'
/home/wizville/.rbenv/versions/2.1.5/lib/ruby/2.1.0/open3.rb:262:in `block in capture3'
/home/wizville/.rbenv/versions/2.1.5/lib/ruby/2.1.0/open3.rb:199:in `popen_run'
/home/wizville/.rbenv/versions/2.1.5/lib/ruby/2.1.0/open3.rb:93:in `popen3'
/home/wizville/.rbenv/versions/2.1.5/lib/ruby/2.1.0/open3.rb:252:in `capture3'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/shell.rb:49:in `execute_open3'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/shell.rb:36:in `block (2 levels) in execute'
/home/wizville/.rbenv/versions/2.1.5/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/shell.rb:35:in `block in execute'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/logger.rb:34:in `call'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/logger.rb:34:in `block in benchmark'
/home/wizville/.rbenv/versions/2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/logger.rb:34:in `benchmark'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/logger.rb:21:in `debug'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/shell.rb:34:in `execute'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/shell.rb:18:in `run'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/tool.rb:92:in `call'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/tool.rb:53:in `new'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/image.rb:492:in `mogrify'
/home/wizville/app/preprod.wizville.fr/shared/bundle/ruby/2.1.0/gems/mini_magick-4.1.0/lib/mini_magick/image.rb:378:in `method_missing'

**Comment by jcoyne** [comment]
@Shopwiz I also get deadlocks with minimagick but I'm not using IMGKit. We've found that switching to posix-spawn (over popen3) fixes the issue: https://groups.google.com/forum/#!searchin/hydra-tech/derivatives$20deadlock/hydra-tech/_L2ysL1A0M8/2agSkvWVFAAJ
